# site settingsa
title: Interrupt LLC.
subtitle:
email: info@interrupt.technology
theme: forty_jekyll_theme
description: '経験豊富なメンバーが<br />ITに関するベストソリューションをご提案します。'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.interrupt.technology" # the base hostname & protocol for your site
author: Naoko Kubo
#street_address:
#city: 日野市
#state: 東京都
#zip_code: 191-0041
#country: 日本
#phone:
future: true
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# build settings
markdown: kramdown
kramdown:
 auto_ids: true
 hard_wrap: true
 syntax_highlighter: rouge

sass:
  style: compressed

###QandASlack
qandaslack:
- question: Slackについて
  answer: '申し込みフォームからお申し込み頂きますと、Interruptから入金のご案内メールをお送り致します。振込先への入金が確認できましたら、再度メールをお送り致します。<br>そのメールに添付の開発委託に関する契約書、NDA(秘密保持)契約書をご確認の上、<br>メール内に記載の電子署名用URLから各契約書へご署名頂き、<br>弊社にて以上のご確認が取れましたら契約完了となり、チャットサービスのご案内メールを速やかにお送り致します。<br>'
- question: 契約更新・お支払いについて
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。
- question: 大きな開発のご依頼について
  answer: 申し込みフォームからお申し込み頂きますと、Interruptからメールをお送り致します。<br>添付の開発の委託に関する契約書、NDA(秘密保持)契約書のご確認、<br>メール内に記載の電子署名用URLから各契約書へのご署名、記載の振込先への料金のお振込をお願い致します。<br>以上のご確認が取れ次第契約完了となり、速やかにチャットサービスのご用意をさせて頂きます。

###Information
information:
- title: 契約までの流れ
  content: '①申込フォームよりお申し込み頂きます。<br>②Slackにて弊社スタッフよりお客様専用チャンネルへご招待致します。<br>(Slackアカウントをお持ちで無い場合はアカウント作成をサポート致します。)<br>③Slackにて業務の概要や申込み内容の確認、料金のお支払い日、サービス開始日などを擦り合わせ、弊社より請求書を発行致します。<br>④弊社にて料金のお支払いが確認できましたら、正式にサービスを開始。ビデオMTGなどで作業スケジュールをすり合わせ、ご依頼の作業へ着手して参ります。'
- title: 契約期間と支払い方法
  content: '契約期間は1ヶ月から選択可能です。1ヶ月毎に更新してご利用頂くこともできますし、ご一括のお支払いで長期間のご契約も可能です。現在ご一括3ヶ月以上のご契約で、1ヶ月につき1万円引きとなる長期契約キャンペーン実施中です。お支払い額は申込後チャットでのカウンセリングにて、業務内容や追加オプションをすり合わせながら決定します。お支払い方法は、銀行振込とPayPayがご利用可能です。お支払い先はお支払い額確定後、弊社より発行する請求書をご参照下さい。'
- title: 更新と解約について
  content: '契約終了日の1ヶ月前になりましたら、チャットサービスにて弊社よりリマインドを致します。<br>その際に、契約更新または契約終了（解約）の旨をお伝えください。<br>途中解約の場合は、チャットサービスにて弊社スタッフへお申し出ください。<br><br><br><span class=caution>※途中解約による返金は行っておりません。</span><br><span class=caution>※契約終了後の余剰工数やビデオMTGの余剰時間の差額返金は行っておりません。</span>'
- title: 使用するチャットサービス
  content: 'WithDOでのチャットサービスは全て「Slack」を使用します。申込フォームにSlackアカウントについての項目がございますので、アカウントの有無やご登録アドレスについてお答えください。<br>アカウントをお持ちでない場合は、弊社スタッフがアカウント作成をサポート致します。<br>Slackについてのご不明点については、弊社お問い合わせよりご質問頂くか、Slack公式ヘルプをご覧ください。<br>'
###Contact
contactType:
- name: お問い合わせ内容を選択してください
- name: With DOについて
- name: 開発のご依頼について
- name: Interruptの開発物について
- name: 利用規約/プライバシーポリシーについて
- name: その他

###Course
course:
- name: デベロッパープラン
  description: アプリやWebサイト、社内用システムツールの新規開発や大型アップデートなど、大きな工数が必要な開発のご依頼にオススメなコースです。<br>稼働工数も月に4人日と全コース内で最も多く、全てのサービスがご利用可能となっているため、私たちが最もお力になれるコースです。<br>ご依頼の開発物が「4人日では足りないかもしれない…！」という場合には、他のコースよりお安く工数の追加をご検討頂けます。
  header_class: styledo1
  table_include: table_develop
  image: /assets/images/develop.jpg
  name_en: develop
  color: colordo1
  tabclass: tab-label1
  price: ■ 月額：150,000円/月
  man-days: ■ 稼働工数：4人日/月
  update: ■ 契約更新：１ヶ月単位
  addition1: 30,000円 + 税 / 1人日
  addition2: 33,000円 + 税 / 1人日

- name: デベロッパープランmin
  description: 既存アプリやWebサイトの運用や保守、簡単なツールの開発などにオススメのコースです。<br>大きな新規開発などのご依頼も承れますが、稼働工数が2日間のためゆっくりな開発となるでしょう。<br>迅速な開発をご要望の方は通常の「デベロッパーコース」をお勧め致します。<br>「デベロッパーコース」での新規開発が落ち着いてきたら、こちらに切り替えて運用していくのもいいかもしれません。
  header_class: styledo2
  table_include: table_develop_min
  image: /assets/images/developmin.jpg
  name_en: developmin
  color: colordo2
  tabclass: tab-label2
  price: ■ 月額：90,000円/月
  man-days: ■ 稼働工数：2人日/月
  update: ■ 契約更新：３ヶ月毎
  addition1: 33,000円 + 税 / 1人日
  addition2: 36,000円 + 税 / 1人日

- name: アジャストプラン
  description: 新しく業務を行う上での環境構築や新規ソフトウェアの導入サポートに加え、データ入力やデバッグのような細かな作業など、<br>「ちょっとそこまで手が回らない…！」という状況にオススメのコースです。<br>稼働工数は1日ですが、チャットサポートはご契約中いつでも使えますので環境構築後、ソフト導入後の不明点にもしっかりお答えします。
  header_class: styledo3
  table_include: table_adjust
  image: /assets/images/adjust.jpg
  name_en: adjust
  color: colordo3
  tabclass: tab-label3
  price: ■ 月額：50,000円/月
  man-days: ■ 稼働工数 1人日/月
  update: ■ 契約更新：３ヶ月毎
  addition1: 22,000円 + 税 / 1人日
  addition2: 24,000円 + 税 / 1人日
- name: メンタープラン
  description: Interruptの開発メンバーがIT分野の質問・相談に迅速にお答えします。<br>ベンチャーなどの企業において「作業は自社チームで行う予定だけど、有識者がいない…」「人手が足りなくて中々新人教育に注力できない」など、<br>そんな時代わりに我々がお答え致します。<br>企業に限らず、個人で学習中の方のメンターとしてもご協力致します。
  header_class: styledo4
  table_include: table_mentor
  image: /assets/images/mentor.jpg
  name_en: mentor
  color: colordo4
  tabclass: tab-label4
  price: ■ 月額：30,000円/月
  man-days: ー
  update: ■ 契約更新：３ヶ月毎
  addition1: ー
  addition2: ー


tooltip:
- name: ITチャットサポート
  description: ITに関連する質問やご相談を24時間365日いつでも送れるチャットサービスです。<br>また、月に合計1時間までビデオMTGも承っております。毎週15分や隔週30分などご要望に合わせたMTGを行えます。<br>進捗確認や翌月以降のスケジューリングにご利用ください。<br>チャットやビデオMTGにご参加頂けるのは1名様までですが、オプションにて参加メンバーの追加も可能です。チャットサービスはSlackを使用します。
  text: ※内容や状況次第ではメッセージへのお返事にお時間を頂く場合がございますので予めご了承ください。<br>※Slackのアカウントをお持ちでない場合は、サービス開始時にアカウント作成をサポート致します。<br>※ビデオMTGの余剰時間の繰越や差額返金は行っておりません。
- name: 開発工数(運用)
  description: 既存Webコンテンツやアプリの追加開発、修正対応及び、<br>新規開発も含めた仕様策定やスケジュール管理、デバッグといったディレクション業務など、<br>開発物の運用を行う際に必要な工数です。
  text: ※開発工数のご利用には、契約書へのご署名をお願いする場合がございます。<br>※工数の有効期間はご契約継続中に限ります。<br>※余剰工数の差額返金は行っておりません。<br>※お支払い後のキャンセルによる返金は行っておりません。

- name: 作業工数
  description: 環境構築、ソフトウェア導入のサポート、データ入力、製品デバッグ、調査、テストプレイなど、<br>開発や業務のサポートを行う際に必要な工数です。<br>事前にお申し込み頂くことで、ご契約期間中毎月定期的に工数を確保することも可能です。
  text: ※工数の有効期間はご契約継続中に限ります。<br>※余剰工数の差額返金は行っておりません。<br>※お支払い後のキャンセルによる返金は行っておりません。
- name: チャットメンバー追加
  description: 基本料に含まれるITサポートチャットの参加メンバーを追加します。
  text: ※追加がない場合、ITサポートチャットの参加人数は原則1名までです。<br>※月の途中からのメンバー追加・脱退による差額の割引・返金は行っておりません。

- name: 申込時 / ご予約
  description: 申込時や申込み直後のMTG、定期MTG、チャットなどで事前に工数をご予約頂いた場合の料金です。<br>工数のご予約はITサポートチャットにてご依頼内容と合わせてお気軽にご相談ください。<br>また、事前にお申し込み頂くことで毎月一定の工数を確保することも可能です。
  text: ※追加でご予約頂いた工数は、別途請求書を発行致します。<br>※余剰工数の差額返金は行っておりません。<br>※お支払い後のキャンセルによる返金は行っておりません。<br>※業務内容や開発スケジュール、納品日などの決まったご依頼から優先的に対応して参ります。<br>　その為、ご予約頂いていても即時対応できない場合がございます。<br>　業務のご依頼、スケジュールの擦り合わせはお早めにお願い致します。

- name: 臨時対応
  description: 予期せぬバグやサーバーの停止、急な予定の変更などで、工数を急遽追加して作業をご依頼頂く場合の料金です。<br>なお、弊社業務状況によっては即時お受けできない場合もございますので、予めご了承ください。<br>臨時対応完了後、工数が余った場合は同じ工数としてご利用可能です。
  text: ※臨時対応時の工数は、別途請求書を発行致します。<br>※余剰工数の差額返金は行っておりません。<br>※お支払い後のキャンセルによる返金は行っておりません。
- name: 開発工数(新規)
  description: Webコンテンツやアプリの新規開発を行う際に必要な工数です。<br>なお、ディレクション工数は新規,既存に関わらず「開発工数（運用）」でのご案内となっています。<br>開発物の立ち上げが完了した後の運用や追加開発は「開発工数（運用）」にて承ります。
  text: ※開発工数のご利用には、契約書へのご署名をお願いする場合がございます。<br>※工数の有効期間はご契約継続中に限ります。<br>※余剰工数の差額返金は行っておりません。<br>※お支払い後のキャンセルによる返金は行っておりません。


plan:
- name: develop
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】＋【開発工数30,000円/1人日×4人日】
  addition1:
    title: 料金内訳
    description: 開発工数30,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数30,000円/1人日 + 20%
  update:
    title: 契約更新
    description: 毎月1ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。
- name: developmin
  pricedesc:
    title: 料金内訳
    description: 料金内訳：【チャットサポート30,000円】＋【開発工数30,000円/1人日×2人日】
  addition1:
    title: 料金内訳
    description: 開発工数30,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数30,000円/1人日 + 20%
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。<br>※初回1ヶ月無料キャンペーン対象プランのため、初回のみ3ヶ月+1ヶ月(無料)の計4ヶ月の契約となります。
- name: adjust
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】＋【作業工数20,000円/1人日】
  addition1:
    title: 料金内訳
    description: 開発工数20,000円/1人日 + 10%
  addition2:
    title:  料金内訳
    description: 開発工数20,000円/1人日 + 20%
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。<br>※初回1ヶ月無料キャンペーン対象プランのため、初回のみ3ヶ月+1ヶ月(無料)の計4ヶ月の契約となります。
- name: mentor
  pricedesc:
    title: 料金内訳
    description: 【チャットサポート30,000円】のみ
  addition1:
    title:
    description:
  addition2:
    title:
    description:
  update:
    title: 契約更新
    description:  3ヶ月毎に3ヶ月分の料金のお支払いをお願い致します。お支払日はご契約日によって異なります。<br>ご契約の詳細については「Information」をご確認ください。<br>※初回1ヶ月無料キャンペーン対象プランのため、初回のみ3ヶ月+1ヶ月(無料)の計4ヶ月の契約となります。
